### ISSUE TITLE
Feature Request: A way to override slide animations

### ISSUE THREAD

**Issue by Ed-Dikotope** [TheOriginalJosh/nativescript-slides#49]
It would be great to be able to override the default slide animation. For instance, like providing animation options just like "ui/frame" allows to fade, flip, curlUp etc... I was only able to hack the `currentPanel` to fadeOut before calling `nextSlide` but the next slide still "slides in"; would like a different animation for that.

**Comment by TheOriginalJosh** [comment]
Hey @Ed-Dikotope thanks for the feedback! unfortunately, I don't think this is really possible with the way the slides are build. Possibly with the fade in and out, but I think it would almost be better to fork the slides into a new project and do it there since it would require changing a good bit.

**Comment by Ed-Dikotope** [comment]
I'll give it a shot 😁
